from django import forms
from .models import TournamentModel

class TorunamentForm(forms.ModelForm):
    player1 = forms.CharField(max_length=150)
    player2 = forms.CharField(max_length=150)
    player3 = forms.CharField(max_length=150)
    player4 = forms.CharField(max_length=150)
    player5 = forms.CharField(max_length=150, required=False)
    player6 = forms.CharField(max_length=150, required=False)
    player7 = forms.CharField(max_length=150, required=False)
    player8 = forms.CharField(max_length=150, required=False)
    player9 = forms.CharField(max_length=150, required=False)
    player10 = forms.CharField(max_length=150, required=False)
    player11 = forms.CharField(max_length=150, required=False)
    player12 = forms.CharField(max_length=150, required=False)
    player13 = forms.CharField(max_length=150, required=False)
    player14 = forms.CharField(max_length=150, required=False)
    player15 = forms.CharField(max_length=150, required=False)
    player16 = forms.CharField(max_length=150, required=False)
    player17 = forms.CharField(max_length=150, required=False)
    player18 = forms.CharField(max_length=150, required=False)
    player19 = forms.CharField(max_length=150, required=False)
    player20 = forms.CharField(max_length=150, required=False)
    player21 = forms.CharField(max_length=150, required=False)
    player22 = forms.CharField(max_length=150, required=False)
    player23 = forms.CharField(max_length=150, required=False)
    player24 = forms.CharField(max_length=150, required=False)
    player25 = forms.CharField(max_length=150, required=False)
    player26 = forms.CharField(max_length=150, required=False)
    player27 = forms.CharField(max_length=150, required=False)
    player28 = forms.CharField(max_length=150, required=False)
    player29 = forms.CharField(max_length=150, required=False)
    player30 = forms.CharField(max_length=150, required=False)
    player31 = forms.CharField(max_length=150, required=False)
    player32 = forms.CharField(max_length=150, required=False)
    player33 = forms.CharField(max_length=150, required=False)
    player34 = forms.CharField(max_length=150, required=False)
    player35 = forms.CharField(max_length=150, required=False)
    player36 = forms.CharField(max_length=150, required=False)
    player37 = forms.CharField(max_length=150, required=False)
    player38 = forms.CharField(max_length=150, required=False)
    player39 = forms.CharField(max_length=150, required=False)
    player40 = forms.CharField(max_length=150, required=False)
    player41 = forms.CharField(max_length=150, required=False)
    player42 = forms.CharField(max_length=150, required=False)
    player43 = forms.CharField(max_length=150, required=False)
    player44 = forms.CharField(max_length=150, required=False)
    player45 = forms.CharField(max_length=150, required=False)
    player46 = forms.CharField(max_length=150, required=False)
    player47 = forms.CharField(max_length=150, required=False)
    player48 = forms.CharField(max_length=150, required=False)
    player49 = forms.CharField(max_length=150, required=False)
    player50 = forms.CharField(max_length=150, required=False)
    player51 = forms.CharField(max_length=150, required=False)
    player52 = forms.CharField(max_length=150, required=False)
    player53 = forms.CharField(max_length=150, required=False)
    player54 = forms.CharField(max_length=150, required=False)
    player55 = forms.CharField(max_length=150, required=False)
    player56 = forms.CharField(max_length=150, required=False)
    player57 = forms.CharField(max_length=150, required=False)
    player58 = forms.CharField(max_length=150, required=False)
    player59 = forms.CharField(max_length=150, required=False)
    player60 = forms.CharField(max_length=150, required=False)
    player61 = forms.CharField(max_length=150, required=False)
    player62 = forms.CharField(max_length=150, required=False)
    player63 = forms.CharField(max_length=150, required=False)
    player64 = forms.CharField(max_length=150, required=False)
    player65 = forms.CharField(max_length=150, required=False)
    player66 = forms.CharField(max_length=150, required=False)
    player67 = forms.CharField(max_length=150, required=False)
    player68 = forms.CharField(max_length=150, required=False)
    player69 = forms.CharField(max_length=150, required=False)
    player70 = forms.CharField(max_length=150, required=False)
    player71 = forms.CharField(max_length=150, required=False)
    player72 = forms.CharField(max_length=150, required=False)
    player73 = forms.CharField(max_length=150, required=False)
    player74 = forms.CharField(max_length=150, required=False)
    player75 = forms.CharField(max_length=150, required=False)
    player76 = forms.CharField(max_length=150, required=False)
    player77 = forms.CharField(max_length=150, required=False)
    player78 = forms.CharField(max_length=150, required=False)
    player79 = forms.CharField(max_length=150, required=False)
    player80 = forms.CharField(max_length=150, required=False)
    player81 = forms.CharField(max_length=150, required=False)
    player82 = forms.CharField(max_length=150, required=False)
    player83 = forms.CharField(max_length=150, required=False)
    player84 = forms.CharField(max_length=150, required=False)
    player85 = forms.CharField(max_length=150, required=False)
    player86 = forms.CharField(max_length=150, required=False)
    player87 = forms.CharField(max_length=150, required=False)
    player88 = forms.CharField(max_length=150, required=False)
    player89 = forms.CharField(max_length=150, required=False)
    player90 = forms.CharField(max_length=150, required=False)
    player91 = forms.CharField(max_length=150, required=False)
    player92 = forms.CharField(max_length=150, required=False)
    player93 = forms.CharField(max_length=150, required=False)
    player94 = forms.CharField(max_length=150, required=False)
    player95 = forms.CharField(max_length=150, required=False)
    player96 = forms.CharField(max_length=150, required=False)
    player97 = forms.CharField(max_length=150, required=False)
    player98 = forms.CharField(max_length=150, required=False)
    player99 = forms.CharField(max_length=150, required=False)
    player100 = forms.CharField(max_length=150, required=False)
    player101 = forms.CharField(max_length=150, required=False)
    player102 = forms.CharField(max_length=150, required=False)
    player103 = forms.CharField(max_length=150, required=False)
    player104 = forms.CharField(max_length=150, required=False)
    player105 = forms.CharField(max_length=150, required=False)
    player106 = forms.CharField(max_length=150, required=False)
    player107 = forms.CharField(max_length=150, required=False)
    player108 = forms.CharField(max_length=150, required=False)
    player109 = forms.CharField(max_length=150, required=False)
    player110 = forms.CharField(max_length=150, required=False)
    player111 = forms.CharField(max_length=150, required=False)
    player112 = forms.CharField(max_length=150, required=False)
    player113 = forms.CharField(max_length=150, required=False)
    player114 = forms.CharField(max_length=150, required=False)
    player115 = forms.CharField(max_length=150, required=False)
    player116 = forms.CharField(max_length=150, required=False)
    player117 = forms.CharField(max_length=150, required=False)
    player118 = forms.CharField(max_length=150, required=False)
    player119 = forms.CharField(max_length=150, required=False)
    player120 = forms.CharField(max_length=150, required=False)
    player121 = forms.CharField(max_length=150, required=False)
    player122 = forms.CharField(max_length=150, required=False)
    player123 = forms.CharField(max_length=150, required=False)
    player124 = forms.CharField(max_length=150, required=False)
    player125 = forms.CharField(max_length=150, required=False)
    player126 = forms.CharField(max_length=150, required=False)
    player127 = forms.CharField(max_length=150, required=False)
    player128 = forms.CharField(max_length=150, required=False)
    player129 = forms.CharField(max_length=150, required=False)
    player130 = forms.CharField(max_length=150, required=False)
    player131 = forms.CharField(max_length=150, required=False)
    player132 = forms.CharField(max_length=150, required=False)
    class Meta:
        model = TournamentModel
        fields = ['name', 'players']
        widgets = {
            'players': forms.HiddenInput()
        }


    def save(self, commit=True):
        return super().save(commit=commit)
