# Generated by Django 3.0.5 on 2020-04-13 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchmodel',
            name='score1',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='matchmodel',
            name='score2',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
