# Generated by Django 3.0.5 on 2020-04-14 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0002_auto_20200413_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchmodel',
            name='score1',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='matchmodel',
            name='score2',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
