# Generated by Django 3.0.5 on 2020-04-14 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0003_auto_20200413_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchmodel',
            name='winner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='tourney.PlayerLeagueModel'),
            preserve_default=False,
        ),
    ]
