# Generated by Django 3.0.5 on 2020-04-17 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0006_matchmodel_loser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchmodel',
            name='loser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loser', to='tourney.PlayerLeagueModel'),
        ),
    ]
