# Generated by Django 3.0.5 on 2020-04-18 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourney', '0007_auto_20200416_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentmodel',
            name='position_priority',
            field=models.CharField(choices=[('Goal Difference', 'Goal Difference'), ('Head to Head Matches', 'Head to Head Matches')], default='1', max_length=150),
        ),
    ]
